# Generated by Django 3.1 on 2020-08-23 20:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_auto_20200821_1050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='todo',
            old_name='datecompleted',
            new_name='datecomepleted',
        ),
    ]
